---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cluster_name: Default
    engine_url: "{{ lookup('env','OVIRT_URL') }}"
    engine_user: "{{ lookup('env','OVIRT_USERNAME') }}"
    engine_password: "{{ lookup('env','OVIRT_PASSWORD') }}"

  roles:
    - ovirt-cluster-upgrade
