---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    engine_url: "{{ lookup('env','OVIRT_URL') }}"
    engine_user: "{{ lookup('env','OVIRT_USERNAME') }}"
    engine_password: "{{ lookup('env','OVIRT_PASSWORD') }}"

    deployment_cluster: Default
    depployment_storage_domain: NFS
    machine_template: rhel75_60G

    httpd_vm:
      cluster: "{{ deployment_cluster }}"
      domain: example.com
      template: "{{ machine_template }}"
      memory: 2GiB
      cores: 2
      ssh_key: ssh-rsa AAA...LGx user@fqdn

    db_vm:
      cluster: "{{ deployment_cluster }}"
      domain: example.com
      template: "{{ machine_template }}"
      memory: 4GiB
      cores: 1
      ssh_key: ssh-rsa AAA...LGx user@fqdn

    vms:
      - name: postgresql-vm-0
        tag: postgresql_vm
        profile: "{{ db_vm }}"
      - name: postgresql-vm-1
        tag: postgresql_vm
        profile: "{{ db_vm }}"
      - name: apache-vm
        tag: httpd_vm
        profile: "{{ httpd_vm }}"

    affinity_groups:
      - name: db-ag
        cluster: production
        vm_enforcing: true
        vm_rule: negative
        vms:
          - postgresql-vm-0
          - postgresql-vm-1

  roles:
    - ovirt-vm-infra
